Neriderc/GVExport

- utils.php
Update depricated curly braces syntax for PHP7.4
> Update braces for PHP7.4

- resources/views/page.phtml
Tidied up some code, including fixing some errors. Some parts retained in comments until I can be sure they are not needed.
> Partially tidied up code

- functions_dot.php
- resources/views/page.phtml
Photos weren't showing when rendered in browser, this is now fixed. Note SVG with photos rendered server side still does not work (did not work before)
> Fix photos in browser

- resources/views/page.phtml
Updating "Show Individual PID" to "Show Individual ID" to align with "Show Family ID". Resolves #47
> Update PID to ID

- resources/views/page.phtml
> Fix for #62

- resources/views/page.phtml
- utils.php
Updated method for translating drop-down lists.
Resolves #71
> Fix issue with translations

- resources/views/page.phtml
This change reverts change of button from "Update" to "Preview" based on discussion in #80
> Change "Preview" back to "Update"

- resources/views/page.phtml
If spacing values are blank or otherwise not numbers, set to default 100%
Resolves #89
> Fix blank nodesep/ranksep

- resources/views/page.phtml
Update the terms used when there are items in the clippings cart
Resolves #97
> Update clippings cart terms

- functions_dot.php
- resources/views/page.phtml
Preferred names (marked with * and displayed underlined in webtrees) are now underlined in GVExport.
Resolves #6
> Underline preferred name

- functions_dot.php
When an individual is adopted, they are not a blood relative (unless also related in a way other than by adoption). This change fixes the colouring of adopted records by updating existing non-functioning code to work with recent versions of webtrees, and then turning this into a function to be called from various places affected.
Resolves #36
> Fix adopted records being wrong colour

- resources/css/gvexport.css
- resources/javascript/gvexport.js
- resources/views/page.phtml
Text input fields now have validation. Max level fields default to 0, DPI field defaults to 72.
Error message added when individual is not selected and browser update or download button clicked.
Resolves #118, #38
> Validate text fields

- config.php
> Declare output variables in case exec disabled

- config.php
- module.php
Attempt to fix issue where exec function disabled by web server
> Check if exec function available

- config.php
Added more robust function for checking for the exec() function being available.
> Change method for detecting if exec available

- functions_dot.php
Update to underline every name marked with asterisk, no matter how many.
Resolves #129
> Support multiple preferred names

- functions_dot.php
Ignore invalid XREF when provided as starting individual
Resolves #142
> Ignore invalid XREF

- functions_dot.php
In combined mode, if a stop individual is selected it is possible a record can be left incomplete. This commit adds a scan to remove family records where there is no spouse or children in combined mode - all records should have a spouse in combined mode. Dummy families (where no spouse exists) are ignored.
Resolves #141
> Fix combined mode with stop indi

- functions_dot.php
- module.php
- resources/css/gvexport.css
- resources/javascript/gvexport.js
- resources/views/page.phtml
Adds support for multiple toast messages, and adds first error message for invalid starting individual XREF
Resolves #146
> Support multiple toast messages

- functions_dot.php
Bug fix to resolve issue introduced where colours are wrong because skip list added to at wrong time
> Fix relatives colouring

- config.php
- functions_dot.php
- module.php
- resources/css/gvexport.css
- resources/javascript/gvexport.js
- resources/views/page.phtml
Group advanced settings together then hide by default. State of advanced settings panel (hidden or shown) is saved once form submitted.
Implements #154
> Hide advanced settings

- config.php
- functions_dot.php
- resources/views/page.phtml
Theme updated with new design
Also:
- Fix for children adopted or pedigree other than by birth showing as non-related even when this option disabled
- Fix for endless loop in specific tree scenario when option to display non-relatives in a different colour is selected
- Fix for page render not generating on page load when scripts load in unusual order (particularly, external script loads before internal script element)
> Update theme for decorated and combined diagram types

- functions_dot.php
Fixes issue where starting individual and spouse are missing if they have a family.
> Fix combined mode

- config.php
- functions_dot.php
- module.php
- resources/views/page.phtml
Adds ability to change font typeface, and set colour of font for name and for other details.
Closes #160
> Allow custom font settings

- functions_dot.php
In some specific scenarios (second individual already part of tree from first individual and individuals are related - relies on being in specific order) then the second starting individual may not have had their descendants included if they were not otherwise included from the first individual.
Fixes #184
> Fix issue with second starting individual

- functions_dot.php
Where multiple starting individuals are selected, we now build independent lists for each then merge them at the end. This is in contrast to having one list updated as we go. It solves the issue of different criteria for different starting individuals (as their generation maxs may have different starting points)
Resolves #184
> Better handling of multiple individuals

- config.php
- functions_dot.php
- module.php
- resources/css/gvexport.css
- resources/javascript/gvexport.js
- resources/views/page.phtml
Arrow colours can now be different based on relationship type (by blood or not by blood). Arrow colours are also now configurable from the UI (default, by blood, not by blood).
Closes #46
> Arrow colour by relation

- config.php
- functions_dot.php
- module.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
When settings changed, automatically update browser render. Includes option to disable.
Closes  #159
> Auto-update browser render

- functions_dot.php
- resources/views/page.phtml
Fixes arrow colour by relationship type not working when items added from clippings cart.
Also resolves issue with combined mode not working when records added from clippings cart
Resolves #197
> Fix arrow colour clippings cart

- functions_dot.php
When no marriage details shown, don't show the family records in combined mode
Resolves #185
> Remove marriage boxes if empty

- config.php
- functions_dot.php
- module.php
- resources/views/page.phtml
Added the ability to abbreviate names.
Resolves #157 
Also allows no names, resolves #157
> Abbreviate names

- functions_dot.php
- resources/views/page.phtml
Resolve issue when name doesn't exist.
Resolve issue when photos are not shown when other details disabled.
Adjust display of diagram when no details included.
Resolve issue in combined mode when top generation individual has multiple marriages - does not resolve issue with other generations.
> Resolve various display issues

- functions_dot.php
- resources/views/page.phtml
This pull request includes:
- Fix for missing parts of tree if "mark non-related in another colour" is not selected
- Fix for tags <U></U> showing in simple mode for individual with preferred name
- Fix for Simple/Decorated/Combined options being on different lines
> Various fixes

- functions_dot.php
> Don't show alt name if names disabled

- resources/views/page.phtml
> Update "Spouses" to "Partners"

- resources/css/gvexport.css
- resources/javascript/gvexport.js
- resources/views/page.phtml
Range of fixes:
Get tomselect URL in a different way to resolve issue with URL Change to avoid occasional issue where render doesn't load first time Handle blank xref issue nicer
New check that we aren't adding duplicate to indi list when two promises triggered at same time for same xref
Related to issue reported in comments of #93
> Fixes for new indi select

- functions_dot.php
Translate codes in dates, e.g. for 'CAL 1 Jan 2000' , convert to 'calculated 1 Jan 2000' and translate. For some, convert to symbols. E.g. convert 'ABT 1 Jan 2000' to '~1 Jan 2000'
Resolves #223
> Symbols for date abbreviations

- functions_dot.php
Forgot to commit this small change as part of #228
> Update spacing for symbols

- functions_dot.php
- module.php
- resources/css/gvexport.css
- resources/javascript/gvexport.js
Many code tweaks with the intention of tidying the code and making no functional changes
> Tidy up code

- resources/css/gvexport.css
- resources/javascript/gvexport.js
- resources/views/page.phtml
First changes for #234
- Add Fullscreen mode
- Scale settings panel to better fit mobile
> Mobile support

- config.php
- functions_dot.php
- module.php
- resources/css/gvexport.css
- resources/views/page.phtml
Added options to change each of the colours used in GVExport that did not already have options.
Closes #195
> Add options to customise colours

- functionsAdmin.php
- module.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
- resources/views/settings.phtml
Default values for settings can now be set in control panel. Defaults for the admin settings are currently still set in config.php though we may decide to change this in future.
Resolves #51
> Set defaults in control panel

- config.php
- functionsAdmin.php
- functions_dot.php
- module.php
- resources/css/gvexport.css
- resources/javascript/gvexport.js
- resources/views/page.phtml
- resources/views/settings.phtml
Added option to highlight starting persons as well as option to configure the highlight colour. Also includes fix for admin page.
> Add option to highlight starting persons

- resources/javascript/gvexport.js
- resources/views/page.phtml
Also scrolls to first individual in list when render generated
Resolves #245
> Scroll render to starting individual when clicked in list

- config.php
- functionsAdmin.php
- functions_dot.php
- module.php
- resources/views/page.phtml
- resources/views/settings.phtml
Added setting for name font size in addition to base font size setting. 
Added ability to change both font size settings in the user interface as well as in the admin panel.
Closes #247
> Add setting for font sizes

- resources/javascript/gvexport.js
- resources/views/page.phtml
This change ensures "scroll to person" feature works at different DPIs
Resolves #273
> Fix scroll with different DPI

- resources/css/gvexport.css
- resources/javascript/gvexport.js
- resources/views/page.phtml
Adds the refreshed person select to the stopping individuals selection.
Closes #251
> Implement fancy person select for stopping indis

- app/Dot.php
- app/help.phtml
- config.php
- module.php
- resources/views/page.phtml
Added debug settings section
Moved debug output to popup log so diagram still shows 
Refactored response data to use JSON to return the DOT file, debug string (if enabled), and any toast messages to show.
Closes #284
> Changes to debug mode to make it easier to use

- app/Cookie.php
- app/Dot.php
- app/functionsAdmin.php
- config.php
- module.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
- resources/views/settings.phtml
Refactor cookies to use JSON format
Rename "Output settings" to "File settings"
Add new "Advanced" section to "File settings"
Add ability to save settings to a file, and load settings from an uploaded file.
Note that choosing to download file settings will trigger an update of the browser render.
Closes #92
> Save settings

- resources/javascript/gvexport.js
Issue meant render would be triggered to refresh many times due to misplaced }. Fixed.
Resolves #301
> Fix mass refresh of render while downloading settings

- resources/javascript/gvexport.js
Update button was not being shown/hidden when auto-update enabled/disabled. Fixes this issue.
> Fix update button show hide

- app/Dot.php
- app/FormSubmission.php
- app/Person.php
- app/Settings.php
- config.php
- module.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
- resources/views/settings.phtml
Resolve issue loading settings from file
Also includes changes to rename settings to shorten the names in anticipation of feature to save multiple versions of settings within webtrees as webtrees has a name length limit and we need space for an ID on the end
> Resolve issue loading settings from file

- app/Dot.php
- app/FormSubmission.php
- app/Person.php
- app/Settings.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
- resources/views/settings.phtml
Added file name, MCLIMIT, and birth/death prefix settings into the admin page.
Attempt to fix issue loading settings from a file
Added some security improvements (escaping user input in various places)
> Multiple saved settings

- resources/javascript/gvexport.js
If auto-update is enabled, now it will auto-refresh the browser rendering after uploading a settings file.
> Reload on settings upload

- app/FormSubmission.php
- config.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
Fixed show/hide of advanced settings when loading from settings file.
Related to conversation in #310
> Fix show/hide of advanced settings

- app/Dot.php
> Fix stop_xref

- app/ApiHandler.php
- app/Settings.php
- resources/css/gvexport.css
- resources/javascript/gvexport.js
- resources/views/page.phtml
If settings are saved with the same name as other settings, these settings are overwritten.
User is prompted before overwriting.
Closes #327
> Allow settings overwrite

- app/settingsLink.php
- module.php
Fixes issue with sharing settings via URL only working is pretty URLs are enabled. Now should work with default URLs.
Closes #336
> Resolve issue with shared setting URL

- resources/javascript/gvexport.js
If we are loading an xref from a starting or stopping individuals list, and the case is incorrect, this is now updated from the webtrees search.
Resolves #338
> Update case of XREF when loading

- resources/javascript/gvexport.js
Fix for diagram not being updated after we correct case of XREF, leading to stop XREF not being honoured until next XREF change.
Resolves small issue with previous pull request #333
> Fix diagram update after XREF correction

- app/ApiHandler.php
- app/Favourite.php
- app/Settings.php
- module.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
Add option to add a saved settings link into the user or tree webtrees favourites.
Option to add to my favourites is only available if logged in.
Option to add to tree favourites is only available if user is a tree manager (i.e. they can add a favourite manually)
Closes #330
> Add to favourites

- app/FormSubmission.php
- app/Person.php
- config.php
- resources/views/page.phtml
Added option allowing user to add list of XREFs that will not be coloured when option to set different background for starting individuals is selected.
Closes #343
> Add option to overwrite starting person highlight

- app/ApiHandler.php
- resources/javascript/gvexport.js
Refactor meant Add to Tree favourites stopped working as ID not passed through. Fixed.
Raised in https://github.com/Neriderc/GVExport/issues/330#issuecomment-1427599960
> Fix add to tree favourites

- resources/css/gvexport.css
- resources/javascript/gvexport.js
- resources/views/page.phtml
With option to highlight starting individuals, we previously added an override list where you could list XREFs that should not be highlighted.
This pull request updates this functionality to instead provide a list of starting individuals with a checkbox next to them. Only starting individuals that have been checked will be highlighted. Unchecked individuals are not highlighted.
Closes #354
> Starting indis

- resources/views/settings.phtml
> Fix error with admin reset link

- app/Cookie.php
- changelog.txt
- module.php
Updated change log
Incremented version number in code
Fixed issue saving named setting when logged out
> Prep release

- resources/css/gvexport.css
- resources/javascript/gvexport.js
- resources/views/page.phtml
This pull request adds a search button to the diagram under the button that makes the diagram full screen.
You search for an individual using the webtrees search. Only individuals present in the diagram will show in the results. Click on a result to scroll the diagram to that individual.
Closes #344
> Search diagram

- resources/css/gvexport.css
- resources/javascript/gvexport.js
- resources/views/page.phtml
Changes to #344
- Adjust alignment of button
- Adjust size of search box if screen too narrow (e.g. mobile)
I've also made changes to the settings panel to display a little better on mobile.
> Adjust diagram search

- resources/css/gvexport.css
- resources/javascript/gvexport.js
- resources/views/page.phtml
A fix to prevent new message from showing every time page loaded, which was caused because indi XREF in URL replaced indi in start list even though both were the same XREF.
Also a change to the diagram search icon to look better on mobile.
> Source indi fix + search icon

- app/Settings.php
- changelog.txt
- resources/css/gvexport.css
- resources/javascript/MainPage/UI.js
Updated changelog
Fixed issue where option to show diagram panel was not saved, resolves #428
Fixed issue with scroll bar in help always showing in Chromium-based browsers (Edge, Chrome, etc), as per comment https://github.com/Neriderc/GVExport/issues/423#issuecomment-1570265322
Fixed issue with JustLight theme where advanced settings buttons weren't correctly detecting new background colour, as per comment https://github.com/Neriderc/GVExport/issues/406#issuecomment-1570221575
> Pre-release fixes

- app/Help.php
- resources/javascript/MainPage/UI.js
- resources/views/page.phtml
Resolved #430 by setting minimum zoom to be much less zoomed in
Resolved issues in comment https://github.com/Neriderc/GVExport/issues/423#issuecomment-1572094420
> Resolve pre-release issues

- resources/javascript/MainPage/SettingsGroup.js
- resources/javascript/gvexport.js
- resources/views/page.phtml
JPG quality setting wasn't always showing. Two scenarios:
- When JPG setting selected
- When setting loaded from saved setting instead of set manually
These are now resolved. Resolves #440
> Resolve issue with JPG quality setting

- app/Dot.php
pls add that to an option for Top/Down Layoute
fixes issue #452
>  show combined boxes Over/Under in Top/Down combined output

- changelog.txt
- module.php
Change log and version update in preparation for new release
> Release preperation

- resources/javascript/MainPage/Data.js
Added flag to compress jsPDF files as large documents were hundreds of MB.
> Compress jsPDF files

- app/Dot.php
- app/FormSubmission.php
- app/Settings.php
- config.php
- resources/views/settings.phtml
Added ∞ symbol as marriage date prefix. Configurable (or removable) by admin only
> Add marriage prefix functionality

- app/Person.php
- app/Settings.php
Added new name abbreviation option "Preferred given name and surname"
> Add Preferred name abbreviation

- app/ApiHandler.php
- app/FormSubmission.php
- app/Settings.php
- changelog.txt
- config.php
- resources/javascript/MainPage/Data.js
- resources/javascript/gvexport.js
- resources/views/ControlPanel/GeneralSettings.phtml
- resources/views/MainPage/GeneralSettings.phtml
- resources/views/MainPage/GeneralSettings/SaveSettings.phtml
Added new option to sort saved settings
Closes #482
> Sort settings

- resources/javascript/MainPage/UI.js
Small correction on previous pull request #489
> Fix URL replacement

- resources/css/gvexport.css
- resources/javascript/MainPage/UI.js
- resources/javascript/gvexport.js
- resources/views/page.phtml
This pull request fixes some minor issues with the new context menu that can show when clicking on an individual when this option is enabled:
- Refactored z-index so now the menu is always shown above the side panels.
- Refactored positioning of menu to be based on viewport to allow attaching to the rendering container. This resolves an issue where the menu did not work in fullscreen mode
- Menu will now hide when the page is scrolled or the diagram is zoomed. This resolves issue where the position of the menu may not align with the individual after the page is moved.
> Fix issues with new context menu

- resources/javascript/MainPage/Data.js
This fixes an issue where settings could not be overwritten.
Fixes #502
> Fix overwriting settings

- resources/javascript/gvexport.js
Fixed debug log button not working, as mentioned in #501
> Fix debug log button not working

- app/Dot.php
- app/Person.php
This resolves an issue where in combined mode if a family exists with no parents then it fails to render the diagram.
Resolves #501
> Resolve issue with parentless family

- app/Dot.php
Fixed display of family record in separated mode broken by recent change.
> Fix family display

- resources/javascript/gvexport.js
Fixed context menu for menu shown on indis to make it close when clicked off the menu
Closes #521
> Fix context menu

- changelog.txt
Update change log in preparation for release
> Release 2.2.0 prep

- app/ApiHandler.php
- app/Favourite.php
- app/OutputFile.php
- module.php
Update to support both webtrees 2.1.x and 2.2.x
Resolves #543
> Support 2.1 and 2.2

- app/Dot.php
- app/FormSubmission.php
- app/Settings.php
- config.php
- resources/javascript/MainPage/SettingsGroup.js
- resources/views/ControlPanel/Appearance.phtml
- resources/views/MainPage/Appearance.phtml
- resources/views/MainPage/Appearance/DiagramAdvanced.phtml
- resources/views/MainPage/Appearance/TileDesign/CustomArrowColourSubgroup.phtml
- resources/views/page.phtml
Add new option to use random colours for arrows.
Partners have matching colours and everyone else is a random colour from a pre-defined list.
Resolves #549
> Random line colours

- app/Dot.php
- app/FormSubmission.php
- app/Settings.php
- config.php
- resources/javascript/MainPage/Form.js
- resources/javascript/gvexport.js
- resources/views/MainPage/Appearance/DiagramAdvanced.phtml
- resources/views/MainPage/Appearance/TileContents.phtml
- resources/views/MainPage/Appearance/TileDesign.phtml
- resources/views/MainPage/Help/Detailed information/Appearance/Diagram.phtml
- resources/views/MainPage/Help/Detailed information/Appearance/Tile contents.phtml
- resources/views/settings.phtml
This pull request combines my other two pull requests, to facilitate your work.
> Handle divorces and pedigree label
