Neriderc/GVExport

- module.php
Updated join() parameter order as passing glue string after array is now deprecated in PHP7.4
> Update join for PHP7.4

- functions_dot.php
The Collection output by `$i->spouseFamilies` was not checked correctly for emptiness, causing all people without a partner to be missing from the Combined diagram type.
The second place I fixed the check has something to do with rendering of families, although I am not quite sure exactly what it changes.
> Fix partner-less people not showing in Combined mode

- functions_dot.php
The option "Mark not blood-related people with different color" is present in the UI, but currently does nothing. 
This PR simply re-adds the lines that were removed. This allows non-blood related people to obtain a color just like the blood-related people instead of just a dull grey background
> Fix "Mark not blood-related" option

- functions_dot.php
- resources/views/page.phtml
This pull request covers two changes:
1. Keep X in corner of options panel (don't scroll it away with the rest of the options) as per #10
2. A small change to account for directory functions sometimes giving full or relative paths to data directory. This change should account for both scenarios.
> X button patch and media file fix

- config.php
- functions_dot.php
- module.php
- resources/views/page.phtml
Previously the "Generate a file for download" setting was not remembered between page loads. This commit should fix this.
> Fix remember download option

- module.php
After fixing the download option so that it was remembered, a bug was introduced where it doesn't work (or perhaps doesn't always work). This fixes this issue.
> Fix for download option

- config.php
Photos in SVG now supported. Requires Cairo for GraphViz, may be supported by default. SVG with images have images embedded, open fine in browser but image viewers seem to have trouble with all by the smallest files (max of about 10 people with photos). Limit seems to be a file size of about 10MB.
> Fix SVG photos

- module.php
- resources/views/page.phtml
Output options that related to appearance (and also affected browser output) have been moved to Appearance section. Have renamed buttons "Preview" and "Download" to represent the browser preview and the output of selected file. This is partly in anticipation of some client side generation of output at a future date.
This should close #34.
> Changes to options

- functions_dot.php
Where another module has already added the PID to the name, remove it before we add our one to prevent duplicates.
Fixes #31
> Fix duplicate PID

- config.php
- functions_dot.php
This commit brings support for gender "Other" (X). Individuals gender "Other" will be shown in the same shade of yellow that webtrees uses. Unknown gender individuals are now green by default, the same shade as webtrees uses.
Resolves #29
> Add support for gender X

- functions_dot.php
- resources/views/page.phtml
For each tree in webtrees there is an option in the control panel indicating if thumbnails should be shown in charts. If this is set to "Hidden", the option to include photos is not shown.
This pull request also includes a UI enhancement where if you select the "Simple" diagram type, the option to include photos is disabled. Selecting another type re-enables the box.
Resolves #54
> Hide photos if disabled

- config.php
- module.php
- resources/views/page.phtml
Only lets you choose DOT as an output format, and gives a message warning that GraphViz is not installed so options are limited.
As client side generation is added, this should still be suitable.
Resolves #76
> Warn if GraphViz not installed

- resources/views/page.phtml
Change "Cousins" to "All relatives". If "All relatives" checked, ensure "Siblings" is also checked. If "Siblings" unchecked while "All relatives" checked, then uncheck "All relatives"
Resolves #79
> Rename "Cousins" and enforce

- config.php
- functions_dot.php
- module.php
- resources/views/page.phtml
This adds the ability to override the cart contents, so settings can be used to select records instead of using the contents of the cart, even if there are items in the cart.
Resolves #52
> Allow override of cart

- functions_dot.php
- module.php
- resources/views/page.phtml
When using the Vesta suite of modules, you can enable an option to show the XREF in the person's name. This means the option to show XREF no longer works.
In this commit, we make a change so that the GVExport option will successfully disable this, but we also change it so that if the option to show XREF in name is enabled in Vesta (or another similar module), then the option to display the XREF on individuals is turned on by default (otherwise it is off by default).
Resolves #91
> Respect XREF setting in Vesta

- config.php
- resources/views/page.phtml
Change default ancestor and descendant levels to 2 to reduce records, then enable loading the browser rendering as soon as page is loaded. Data from cookie used instead of defaults if cookie is set.
Resolves #99
> Render in browser on page load

- functions_dot.php
If adopted person was chosen as starting individual, siblings were assumed as related and this spread through the tree. Fixed by adding check for if the individual being added is not related to their own family, if they aren't related then set $rel to false for this round of recursion.
> Fix related colours when starting from adopted individual

- resources/views/page.phtml
When items in clippings cart, the option to ignore was not working as when branches had been merged some of the old code was merged in. This resolves the issue.
> Fix clippings cart options

- functions_dot.php
When starting indi is adopted, grandparents were not shown for mother if "spouses" option checked, but worked fine otherwise. This was because indi's father was added, then the spouse of father, then mother. Because mother already existed, and "anyone" option not set, link to grandparents not followed. Updated to ignore spouse link if adopted setting set to "BOTH", as we know mother will be added by mother link.
Resolves #124
> Fix grandparents not being shown for adopted starting indi

- resources/views/page.phtml
When hovering over a family record, a messy version of the contents of the record was shown. When hovering over a URL on an individual, it showed "<TABLE>". It also showed "WT_Graph" when hovering in blank space. This now shows nothing when in blank space, and the XREF of the record when hovering over a record.
> Tidy hover text

- functions_dot.php
Currently, when the related option is set, this only checks the displayed records. Where the link is not in the displayed records, the related status is shown as not related. This update will scan the full tree for relatives of starting persons, in order to determine whether an individual is related to the starting person.
Resolves #109 and may resolve several other issues.
> Update related checking to improve accuracy

- config.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
Add ability to download some image formats via client side javascript. Check for GraphViz installation, if installed use this, otherwise use client side.
Includes SVG, PNG, JPEG options.
Resolves #23  and #25
> Add client side image download

- functions_dot.php
This pull request updates the check so any relationship type is treated as non-relative except for "BIRTH" and not having a pedigree declared.
Resolves #140
> Fix foster child showing as blood related

- functions_dot.php
This resolves an issue where an adopted child is shown as not being related to their birth parents if their adopted parents were added first while crawling the tree
> Fix issue with adopted child

- resources/javascript/gvexport.js
This introduces a more robust search for the image tags, that works regardless of the order of the attributes. This is necessary as for some reason Firefox and Chromium based browsers have their tags in a different order
Resolves #139
> Fix export in Edge/Chrome

- changelog.txt
- module.php
This pull request adds version checking and updates the changelog (which was quite out of date).
Original post:
@hartenthaler I've made the changes as you've suggested in #69, but I don't see any warnings about the version.
I have set the latest-version.txt to have 2.1.9 and set the CUSTOM_VERSION constant to 2.1.8. I notice in the admin panel the current version of the module now shows, however, I don't get a warning about there being a new version.
Do checks happen on a schedule or should it work instantly?
I've created this pull request so you can see the changes I've made in case I've got something wrong.
> Check latest version

- module.php
- resources/views/page.phtml
After generating the browser output, the output file type was always set to "dot" due to the output being changed to dot by javascript in order to have the dot string returned for displaying in the browser. This changes this so that the output type is not changed, and instead the backend will use "dot" as a value if the $browser variable is true but not change the form or save dot in the cookie.
Resolves #156
> Remember output type

- resources/views/page.phtml
Fields for spacing between generations/individuals were not aligned with other fields. This resolves #168
> Fix spacing of space settings

- functions_dot.php
When option to mark non-blood relatives in a different colour is selected, children linked other than by birth were being marked in a different colour. This change ensures all individuals are shown the same if this option is disabled.
> Fix issue with adopted being in different colour when disabled

- changelog.txt
- resources/css/gvexport.css
Top-aligned the checkboxes that go with the settings to enable of disable blood relatives being a different colour
Fixes #179
> Adjust checkbox alignment

- resources/views/page.phtml
If the session is no longer valid in webtrees (e.g. you logged out in another window or your login has timed out), then an error is shown as a toast message.
Closes #186
> When login expired, reload page

- functions_dot.php
Remove check that removes families with no parents or children. If these records are part of our tree, we should show them. Even if they can't be nicely linked.
Resolves #187
> Fix missing records in combined mode

- functions_dot.php
- resources/views/page.phtml
This pull request resolves #198, where records are no listed in combined mode if there are no spouse all children in the diagram. Disabling spouses should not cause all these records to disappear, it is due to a check that is intended to resolve issue #141 with a half-complete record being shown. But if spouses are unselected, then a family with one spouse is not half-complete. This resolves this issue. 
It also contains a fix for a situation where the blood-relationship status could be wrong if an adopted starting individual had adopted siblings who were blood related to the parents/family.
> Fix combined mode

- resources/javascript/gvexport.js
- resources/views/page.phtml
If you change the starting individual, then refresh the page, they are reset to the original because the XREF is in the URL. This commit updates the URL with the new indi XREF so a refresh will remember the same indi.
Resolves #207
> Fix selected indi being reset

- functions_dot.php
If related individuals option was selected, sometimes different indis would be shown than when it wasn't selected. This change updates the code to ensure the same indis are shown (going with what is displayed when the option is enabled)
> Resolve issue with related setting

- functions_dot.php
Alternate name was causing error due to not being parsed through the name formatter. This update fixes this.
Resolves #212
> Fix alternate name

- functions_dot.php
If individual has secondary name (name in another script), then abbreviate this as well. If option for initials is shown, do not show alternate name at all as this isn't working properly.
Related to #212
> Abbreviate secondary name

- resources/css/gvexport.css
Set a minimum height for rendering to help with display on non-desktop devices
Related to #219
> Rendering minimum height

- config.php
- resources/views/page.phtml
Remove MCLIMIT setting from UI. This setting appears to do nothing, at least in the context of GVExport. Retained in config.php in case it is needed by users. Default now 1 instead of 50.
Resolves #163
> Remove MCLIMIT

- resources/javascript/gvexport.js
When one record in indi list and same indi is in URL, this can lead to duplicates because two promises are triggered. This fix attempts to resolve this.
> Fix duplicates in selection list

- config.php
- functions_dot.php
If font not found, instead of defaulting straight back to default font (Arial), instead try generic family. For example, if Times New Roman not found, default to Serif. This should work better on mobile where standard websafe fonts are not available.
Closes #219
> Add fallback fonts of same generic family

- functions_dot.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
Treat descent level 0 and disabled descendants the same.
Add spouses to youngest generation (when enabled)
Family records with no children and only one partner are no longer shown in Decorated and Simple mode.
Resolves #201
Also a small change to the starting individual selection to resolve a bug with the XREF listed in the URL being added again on page refresh when it had previously been removed.
> Change descendants

- functions_dot.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
Instead of having the same icon, now an X shows to close fullscreen mode.
Also contains two minor changes:
- Fix for webtrees footer being partially covered
- Fix for links not opening in new tab in some cases
Related to #234
> Add X for closing fullscreen

- resources/css/gvexport.css
- resources/views/page.phtml
Panzoom library prevents touch actions by default. We disable this, but then need to add CSS to stop weird stuff happening (specifically: touch-action: none added to stop page scrolling when render is dragged).
Resolves #249
> Fix links on mobile

- functionsAdmin.php
- resources/views/page.phtml
Enable including photos by default, then move the photos, links, abbreviations to advanced section
Closes #252
> Move links/photos/abbreviations to advanced

- resources/javascript/gvexport.js
- resources/views/page.phtml
When dragging the browser rendering, if we start dragging on a tile then when we stop dragging a new window is opened with the record as if we had clicked on it. This change means we don't trigger the click if dragged more than the minimum distance (currently 100 pixels)
Resolves #253
> Don't click if dragging

- functions_dot.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
Combined mode does not hold individual IDs so could not scroll to these records when starting person clicked on. This change updates the node name for family records in combined mode to have the XREF of the individuals contained. A small change is made to support this change in the function to scroll to a person.
Resolves #266
> Fix scroll to person for combined mode

- resources/views/page.phtml
If graphviz installed, note that browser, svg, and pdf all support URLs. If graphviz not installed, note just browser and svg as  client-side pdf does not support links.
Closes #260
> Tweak text based on if graphviz installed

- functions_dot.php
Image resolution for client side images was set at a fixed size, now it's based on DPI.
Closes #259
> Image resolution based on DPI

- app/ImageFile.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
Resolves #280 where PDF (and sometimes other files) could not be downloaded if GraphViz not installed on server. 
Also includes an additional check to protect original media files when resizing, and some additions to help with automated frontend testing.
> Fix issue with jsPDF

- resources/views/page.phtml
When loading the diagram, scroll to the last XREF on the list so when a new starting person is added, it will scroll to them.
Closes #285
> Scroll to last person on list not first

- app/Cookie.php
- app/Dot.php
- module.php
If there are multiple trees, switching between them now saves settings separately.
Closes #293
> Save settings per tree

- app/Dot.php
- app/Person.php
XREFs were always shown regardless of setting after recent refactor, this is now fixed.
This is a symptom of a structure issue but for now I've just done a quick fix.
> Fix show xref

- module.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
Instead of assuming it never happens, now we default to an XREF if none is provided. This is in the following order: First, prefer XREF in URL
Next, prefer XREF of user, if user is linked to an individual 
Last. let webtrees pick, using "significantIndividual" check.
> Default to XREF if no XREF provided

- app/Cookie.php
- app/Dot.php
- app/OutputFile.php
- app/Settings.php
- module.php
- resources/views/page.phtml
- resources/views/settings.phtml
If user is logged in, we now use the webtrees user preferences to save the settings instead of cookies. For logged out users, cookies are still used.
Closes #307
> Don't use cookies for logged in user

- app/Settings.php
- resources/javascript/gvexport.js
- resources/views/page.phtml
When saving preferences, all values are converted to strings. The change to using preferences instead of cookies caused an unseen issue with boolean values. This change should resolve that though there are no user visible impacts from this.
Added error message if a setting in the settings file doesn't exist on the page.
XREF list now refreshed with changes in the advanced list of XREFs when clicking the main Update button when auto-update disabled.
> Refactor saved settings

- resources/javascript/gvexport.js
As per #329 if you enter a lower case ID the stop person does not work but the person is loaded to the list ok.
XREFs are not case sensitive, so solution is to upper case the list.
Also made change to pulling of person data from webtrees, checking that the returned XREF is the same as searched for. This resolves an issue where another record could be returned if the XREF also appeared in a name or other searchable field.
Resolves #329
> Resolve issue with case in IDs

- resources/javascript/gvexport.js
When downloading a settings file, these are specific to a tree. Added tree name to name of file.
As per comment https://github.com/Neriderc/GVExport/issues/330#issuecomment-1427599960
> Add tree name to downloaded settings file name

- app/ApiHandler.php
- module.php
- resources/javascript/gvexport.js
When loading settings from a URL token, if the settings have auto-update disabled then don't hide the settings panel.
Also includes some minor refactoring, and a change to loading the token as it was unreliable as to whether the diagram would be loaded when the page loaded if auto-update was off. It would still update if auto-update was on in the saved form (i.e. last time form was loaded). This change fixes this.
Resolves #346
> Don't hide sidebar

- resources/views/settings.phtml
When not using pretty URLs, the admin settings reset does not work. This has been fixed by adjusting the URL based on if there are already parameters or not.
#364
> Fix reset admin settings for standard URLs

- app/Cookie.php
- app/Settings.php
- config.php
Cookies are limited to 4MB, and saving settings to a cookie takes about 2.5MB. This commit adds an option to compress the data using gzdeflate. Only available in config file, enabled by default. This reduces size by about 40%.
Note that only logged out users use cookies, and only one cookie is saved per tree.
Resolves #365
> Add option to compress cookie

- app/Help.php
Added function to help class to translate the help text, then clean problematic things since translation is added to javascript code. Removes line breaks and converts apostrophes to HTML code equivalent.
#369
> Add function to translate and clean

- resources/views/page.phtml
Changed default zoom level to always be the same, zoomed in on the starting person and surrounding individuals, regardless of diagram size.
Closes #456
> Change default zoom

- app/Dot.php
- app/Settings.php
- config.php
Fixes issue with preferred names not displaying properly.
Issue still occurs when browser cannot load selected font, but most font options should now work ok on Windows, and the default Arial should work ok on all systems.
> Remove font defaults

- resources/javascript/gvexport.js
Webtrees 2.1.19 has a backend change that breaks person selection for GVExport. This update resolves it, but breaks support for previous webtrees versions.
> Resolve issue with webtrees 2.1.19

- module.php
If a user did not have access to the module assigned to them, they could still view the module if they went to the URL.
This fixes this issue by adding an auth check when loading the page.
Resolves #479
> Fix auth issue

- app/ApiHandler.php
- app/Cookie.php
- app/FormSubmission.php
- app/Settings.php
- module.php
- resources/javascript/MainPage/Data.js
- resources/javascript/gvexport.js
- resources/views/MainPage/Appearance/TileDesign.phtml
- resources/views/MainPage/GeneralSettings/SaveSettings.phtml
- resources/views/page.phtml
Changes to logged out users where settings are stored in browser, a small number of visible settings are stored in cookie so they are set when page loads. Remaining settings are loaded via javascript after page has loaded.
This required some changes to how things work.
API request for settings for logged out users now takes this from the form submission not from the cookie.
Added cookie context for settings to set which fields are in cookie.
Some changes to rendering diagram - first render does not store data to avoid saving defaults over user settings
Add ability for logged out users to use shared note colours.
Closes #463
> Refactor settings, enable shared note colour for logged out users

- resources/javascript/MainPage/UI.js
This pull request fixes two bugs related to the context menu that shows when clicking on an individual in the diagram if this is enabled:
- Resolves placement of menu being off if page has been scrolled
- Updates functions that rely on the URL to account for the URL sometimes showing '%2F' instead of '/'
> Fix context menu bugs

- app/MainPage.php
- resources/css/gvexport.css
- resources/javascript/MainPage/UI.js
- resources/views/ControlPanel/DebugPanel.phtml
- resources/views/MainPage/Appearance.phtml
- resources/views/MainPage/Appearance/DiagramAdvanced.phtml
- resources/views/MainPage/Appearance/DiagramType.phtml
- resources/views/MainPage/Appearance/GraphDirection.phtml
- resources/views/MainPage/Appearance/TileContents.phtml
- resources/views/MainPage/Appearance/TileDesign.phtml
- resources/views/MainPage/Appearance/TileDesign/Subgroup.phtml
- resources/views/MainPage/DebugPanel.phtml
- resources/views/MainPage/GeneralSettings.phtml
- resources/views/MainPage/GeneralSettings/BrowserRender.phtml
- resources/views/MainPage/GeneralSettings/MessageHistory.phtml
- resources/views/MainPage/GeneralSettings/OutputFile.phtml
- resources/views/MainPage/GeneralSettings/SaveSettings.phtml
- resources/views/MainPage/GeneralSettings/SettingsFile.phtml
- resources/views/MainPage/PeopleToInclude.phtml
- resources/views/MainPage/PeopleToInclude/ConnectionsToInclude.phtml
- resources/views/MainPage/PeopleToInclude/IncludeAnyoneRelatedTo.phtml
- resources/views/MainPage/PeopleToInclude/ItemsInClippingsCart.phtml
- resources/views/MainPage/PeopleToInclude/NonRelatives.phtml
- resources/views/MainPage/PeopleToInclude/StopProcessingOn.phtml
- resources/views/MainPage/PeopleToInclude/TreatmentOfSourceIndividuals.phtml
- resources/views/MainPage/PeopleToInclude/XrefOfIncludedIndividuals.phtml
- resources/views/page.phtml
- resources/views/settings.phtml
Many colours in GVExport are hard coded, so this is an attempt to use the available CSS variables.
Some minor visual changes, but I've used Javascript to try to keep the default theme similar, and have added custom CSS to use the Primer theme better.
Resolves #505
> Refactor colours to use themes

- app/FormSubmission.php
- app/Person.php
- config.php
- resources/views/MainPage/Appearance/TileContents.phtml
- resources/views/MainPage/Help/Detailed information/Appearance/Tile contents.phtml
Added new option "Use similar events if information not available" in Appearance->Tile contents->Information on individuals.
This option is enabled by default to keep current functionality, where we use webtrees functions to get the dates and places of birth and death.
Disabling this option now bypasses the webtrees functionality and directly checks for a BIRT or DEAT event, preventing christening, baptism, burial, or cremation dates and places from being used for births and deaths.
Closes #498
> Add option to decide if similar events are used to present dates and places of birth and death

- app/FormSubmission.php
- app/Settings.php
- config.php
- module.php
- resources/css/gvexport.css
- resources/javascript/MainPage/Form.js
- resources/javascript/gvexport.js
- resources/views/MainPage/PeopleToInclude/ConnectionsToInclude.phtml
- resources/views/settings.phtml
As per #500, this pull request adds an admin setting to limit the size of the diagram that a user can set. This is intended to help reduce strain on the server, and can be set based on the user's role.
If the limit is 10, this means the user can set up to 10 levels for ancestors and additionally up to 10 levels for descendants (a total of 20 levels).
The default settings are reasonably high, which should mean existing users shouldn't have an issue. You can change the settings in the control panel.
The default settings are:
Visitor: 5
Member: 10
Editor: 15
Moderator: 20
Manager: 25
Admins have a limit of 99 which is the existing limit, however this is now enforced in the backend not only in the website.
Note that we do not have admin help pages, so this is not explained in any detail …
> Add limit to max levels

- resources/css/gvexport.css
- resources/javascript/MainPage/Form.js
Undo a change that cut individuals names short in the lists of individuals in the settings, and returned to previous approach of having the name wrap to the next line. Highlighted individuals will still be cut off due to limited space available.
As per https://github.com/Neriderc/GVExport/pull/509#issuecomment-2444067793
> Restore line wrap to start and stop individuals list

- app/Settings.php
- module.php
When resetting user settings, the maximum level of ancestors/descendants was defaulting to 0. Fixes #518
> Fix max levels defaulting to 0 on reset

- app/ApiHandler.php
- app/FormSubmission.php
- app/Settings.php
- module.php
- resources/javascript/MainPage/Data.js
- resources/javascript/gvexport.js
- resources/views/MainPage/Translations.phtml
- resources/views/page.phtml
Here is the replacement attempt at this. Added message when downloading to say how many individuals and families in generated diagram.
This does not work when you are generating SVG from the browser, because this option simply saves what you see into a file. All other options contact the server when generating (even if you don't have Graphviz on the server), and so this works with everything else (including SVG when generated on the server).
This closes #526, which also has some more information about the approach.
Basically I generate a UUID (or time based token if UUID is not available since this requires secure connection to site). Then I send this UUID with the diagram settings. The page then starts sending requests to the server with the UUID to check session storage for the counts …
> Add download message

- app/Dot.php
- app/Settings.php
- resources/views/MainPage/Help/Detailed information/Appearance/Tile contents.phtml
Added new option to place name abbreviations, to only show the city (i.e. just the part up to the first comma).
Partly addresses #515
> City only abbreviation

- app/Person.php
When rounded corners of indi tile is enabled , the stripe overflows the corners. This change shortens the stripe when rounded corners are enabled.
Fixes #516
> Fix stripe overflowing rounded corners

- resources/javascript/gvexport.js
Fixed issue where the xref in the URL was not loaded into the settings if the user was logged out, due to a timing issue.
Fixed #547
> Fix loading xref from url

- resources/javascript/gvexport.js
Second attempt at fixing #547 
This pull request changes asynchronous request to retrieve settings from browser storage to use await so that loading XREF from URL is not overwritten by settings loaded from browser storage.
Additionally resolves a minor issue with an error being logged to console on page load, and also resolves what may have been an existing issue where starting indi list isn't properly set when user settings are reset.
> Fix url xref

- resources/views/page.phtml
Fixed issue where jsPDF was not loaded in the browser when Graphviz installed on server, but some options require the PDF to be generated in the browser.
Removed conditional include and now jsPDF will always be loaded.
Resolves #552
> Fix issue using PDF

- resources/views/page.phtml
Fixes issue where filename setting is not respected if Graphviz is not installed on the server
Fixes #559
> Fix download filename

- app/OutputFile.php
Updated exec to proc_open if available in order to resolve issue with SERVER_NAME being set and causing Graphviz to refuse to load images from files.
Retained exec fallback if needed.
Resolves #558
> Change how Graphviz is called on server

- app/Dot.php
- app/FormSubmission.php
- app/Person.php
- config.php
- resources/javascript/MainPage/Form.js
- resources/javascript/gvexport.js
- resources/views/MainPage/Appearance/TileContents.phtml
- resources/views/MainPage/Help/Detailed information/Appearance/Tile contents.phtml
This pull request fixes the following issues raised in #571:
- Divorce details now on new line when marriage place enabled
- Changed divorce prefix to the divorce symbol ⚮
- Font size for details now used for arrow labels
- Added option to show or hide marriages, and marriage options are grouped under this.
Resolves issue where coloured stripe doesn't fill whole width if extra images are shown, from issue #572
Resolves issue with parenthesis in secondary name, from issue #573
> Various reported fixes
